### ISSUE TITLE
this is probably a dumb question but how do i fix " no headers found"?

### ISSUE THREAD

**Issue by ryawann** [diyelectromusic/sdemp#1]
im using ubuntu :)

copy and posted error:

Sketch uses 5170 bytes (16%) of program storage space. Maximum is 32256 bytes.
Global variables use 468 bytes (22%) of dynamic memory, leaving 1580 bytes for local variables. Maximum is 2048 bytes.
Invalid library found in /home/ryawan/Arduino/libraries/MP3_Shield_RealtimeMIDI: no headers files (.h) found in /home/ryawan/Arduino/libraries/MP3_Shield_RealtimeMIDI
Invalid library found in /home/ryawan/Arduino/libraries/ArduinoMIDIVS1053Synth: no headers files (.h) found in /home/ryawan/Arduino/libraries/ArduinoMIDIVS1053Synth

did i miss something in the github or something? does this error mean its not going to work?

**Comment by diyelectromusic** [comment]
My apologies!  I hadn't noticed you'd logged this :)

I don't know about the MP3_Shield_ReadltimeMIDI thing - I'm not sure that is one of mine?  With regards to the ArduinoMIDIVS1053Synth error, it looks like you may have installed it into the libraries area, not the src area.  So maybe the same issue relates to the other error you're seeing too.

I'm guessing from the fact you logged this is March (sorry again!) you've either solved it yourself or moved on by now!!

Kevin
