### ISSUE TITLE
freezes miniDexed via USB Midi

### ISSUE THREAD

**Issue by Sebizarro** [diyelectromusic/sdemp#3]
Hi, thanks for sharing this code, very useful for the piano toys keyboards, helped with the matrix decoding.
When i tried with the miniDexed it freezes the minidexed menu. the keyboard still works and sound keeps playing.
Any idea? I dont know much about Midi, but with the keystep it works ok.

thanks again
sb

**Comment by diyelectromusic** [comment]
Hi there, sorry I missed your comment (I must have a look at how notifications are set up on GitHub for me!).

If you are using one of the CircuitPython projects, then there is a known issue with CircuitPython and USB MIDI.  The answer is a custom boot.py file on your Pico that disables the USB HID functionality and just leaves USB MIDI.  You can find details of the workaround here: https://github.com/probonopd/MiniDexed/wiki/Files#cmdlinetxt

If you are having issues with something else let me know which project you're trying to build and I'll have another look!

Kevin

**Comment by Sebizarro** [comment]
Hi @diyelectromusic 

I changed to micropython and added midi DIN 5 out, works great (:  
the midi in on the minidexed and it is  also working (:
trying to add oled and encoder for changing midi channel but didn't work yet.

Thanks for all the support

Sebastião
